#!/bin/bash
# Bash generated by Copilot
# =============================================================
# Build and Push the Service Pack Release Dashboard Image
# Supports both Podman and Docker
# =============================================================
#
# Usage:
#   ./docker/build-push.sh [options]
#
# Options:
#   --version VERSION    Set version tag (default: reads from package.json)
#   --push               Push image to Artifactory after building
#   --latest             Also tag as :latest when pushing
#   --runtime RUNTIME    Container runtime: podman, docker, or auto (default: auto)
#   --dry-run            Show commands without executing
#   -h, --help           Show this help message
# =============================================================

set -euo pipefail

# =====================================================================
# CONFIGURATION - MODIFY REPO_PATH TO MATCH YOUR APPROVED JFROG PATH
# =====================================================================
REGISTRY="dl-innersource-docker-local.artifactory-ehv.ta.philips.com"
REPO_PATH="dxr-apps/service-pack-release-dashboard"
IMAGE_PREFIX="${REGISTRY}/${REPO_PATH}"

IMAGES=(
    "standalone:docker/Containerfile"
)
# =====================================================================

VERSION=""
PUSH=false
TAG_LATEST=false
DRY_RUN=false
RUNTIME="auto"

while [[ $# -gt 0 ]]; do
    case $1 in
        --version) VERSION="$2"; shift 2 ;;
        --push) PUSH=true; shift ;;
        --latest) TAG_LATEST=true; shift ;;
        --runtime) RUNTIME="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        -h|--help) head -n 20 "$0" | tail -n +2 | sed 's/^# //' | sed 's/^#//'; exit 0 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

detect_runtime() {
    if [[ "$RUNTIME" != "auto" ]]; then
        command -v "$RUNTIME" &>/dev/null || { echo "Error: $RUNTIME not found" >&2; exit 1; }
        echo "$RUNTIME"; return
    fi
    if command -v podman &>/dev/null; then echo "podman"
    elif command -v docker &>/dev/null; then echo "docker"
    else echo "Error: Neither podman nor docker found" >&2; exit 1; fi
}

CONTAINER_RUNTIME=$(detect_runtime)
cd "$(dirname "$0")/.."

if [[ -z "$VERSION" ]]; then
    if [[ -f "package.json" ]]; then
        VERSION=$(grep '"version"' package.json | head -1 | sed 's/.*: *"\([^"]*\)".*/\1/')
    else
        VERSION="0.1.0"
    fi
    echo "Using version: $VERSION"
fi

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

run_cmd() {
    if [[ "$DRY_RUN" == true ]]; then echo "[DRY-RUN] $*"
    else echo ">>> $*"; "$@"; fi
}

build_image() {
    local image_name="$1" dockerfile="$2"
    local full_tag="${IMAGE_PREFIX}/${image_name}:${VERSION}"
    [[ ! -f "$dockerfile" ]] && { echo "Skipping $image_name: $dockerfile not found"; return 1; }
    echo "Building: ${full_tag}"
    run_cmd $CONTAINER_RUNTIME build \
        --file "$dockerfile" --tag "$full_tag" \
        --label "org.opencontainers.image.version=${VERSION}" \
        --label "org.opencontainers.image.created=${BUILD_DATE}" \
        --label "org.opencontainers.image.revision=${GIT_SHA}" .
    [[ "$TAG_LATEST" == true ]] && run_cmd $CONTAINER_RUNTIME tag "$full_tag" "${IMAGE_PREFIX}/${image_name}:latest"
}

push_image() {
    local image_name="$1" full_tag="${IMAGE_PREFIX}/${1}:${VERSION}"
    echo "Pushing: ${full_tag}"
    run_cmd $CONTAINER_RUNTIME push "$full_tag"
    [[ "$TAG_LATEST" == true ]] && run_cmd $CONTAINER_RUNTIME push "${IMAGE_PREFIX}/${image_name}:latest"
}

echo "================================================"
echo "Service Pack Release Dashboard - Image Builder"
echo "Runtime:     $CONTAINER_RUNTIME"
echo "Registry:    $REGISTRY"
echo "Repository:  $REPO_PATH"
echo "Version:     $VERSION"
echo "Git SHA:     $GIT_SHA"
echo "================================================"

IMAGES_BUILT=()
for entry in "${IMAGES[@]}"; do
    name="${entry%%:*}"
    dockerfile="${entry#*:}"
    if build_image "$name" "$dockerfile"; then
        IMAGES_BUILT+=("$name")
    fi
done

if [[ "$PUSH" == true ]]; then
    for name in "${IMAGES_BUILT[@]}"; do
        push_image "$name"
    done
fi

echo ""
echo "Done! Images built:"
for name in "${IMAGES_BUILT[@]}"; do
    echo "  - ${IMAGE_PREFIX}/${name}:${VERSION}"
    [[ "$TAG_LATEST" == true ]] && echo "  - ${IMAGE_PREFIX}/${name}:latest"
done
