# PowerShell generated by Copilot
# =============================================================
# Build and Push the Service Pack Release Dashboard Image
# Supports both Podman and Docker
# =============================================================
#
# Usage:
#   .\docker\build-push.ps1 [-Version <version>] [-Push] [-Latest] [-DryRun] [-Runtime <podman|docker>]
#
# Examples:
#   .\docker\build-push.ps1                          # local build only, auto-detect runtime
#   .\docker\build-push.ps1 -Runtime podman           # force Podman
#   .\docker\build-push.ps1 -Version "1.0.0" -Push -Latest
# =============================================================

param(
    [string]$Version = "",
    [switch]$Push,
    [switch]$Latest,
    [switch]$DryRun,
    [ValidateSet("podman", "docker", "auto")]
    [string]$Runtime = "auto"
)

# =====================================================================
# CONFIGURATION - MODIFY REPO_PATH TO MATCH YOUR APPROVED JFROG PATH
# =====================================================================
$REGISTRY = "dl-innersource-docker-local.artifactory-ehv.ta.philips.com"
$REPO_PATH = "dxr-apps/service-pack-release-dashboard"
$IMAGE_PREFIX = "$REGISTRY/$REPO_PATH"

$IMAGES = @(
    @{name = "standalone"; dockerfile = "docker/Containerfile"}
)
# =====================================================================

function Get-ContainerRuntime {
    if ($Runtime -ne "auto") {
        $cmd = Get-Command $Runtime -ErrorAction SilentlyContinue
        if (-not $cmd) { throw "$Runtime is not installed or not in PATH" }
        return $Runtime
    }
    $podman = Get-Command "podman" -ErrorAction SilentlyContinue
    if ($podman) { return "podman" }
    $docker = Get-Command "docker" -ErrorAction SilentlyContinue
    if ($docker) { return "docker" }
    throw "Neither podman nor docker found in PATH."
}

$ContainerRuntime = Get-ContainerRuntime

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
Set-Location $ProjectRoot

if ([string]::IsNullOrEmpty($Version)) {
    if (Test-Path "package.json") {
        $packageJson = Get-Content "package.json" | ConvertFrom-Json
        $Version = $packageJson.version
    } else {
        $Version = "0.1.0"
    }
    Write-Host "Using version: $Version"
}

$BuildDate = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
try { $GitSha = git rev-parse --short HEAD 2>$null } catch { $GitSha = "unknown" }
if (-not $GitSha) { $GitSha = "unknown" }

function Invoke-BuildCommand {
    param([string]$Command, [string[]]$Arguments)
    $fullCmd = "$Command $($Arguments -join ' ')"
    if ($DryRun) {
        Write-Host "[DRY-RUN] $fullCmd" -ForegroundColor Yellow
        return
    }
    Write-Host ">>> $fullCmd" -ForegroundColor Cyan
    & $Command @Arguments
    if ($LASTEXITCODE -ne 0) { throw "Command failed with exit code $LASTEXITCODE" }
}

function Build-Image {
    param([string]$ImageName, [string]$Dockerfile)
    $fullTag = "$IMAGE_PREFIX/${ImageName}:$Version"
    Write-Host "`nBuilding: $fullTag" -ForegroundColor Green
    $buildArgs = @(
        "build", "--file", $Dockerfile, "--tag", $fullTag,
        "--label", "org.opencontainers.image.version=$Version",
        "--label", "org.opencontainers.image.created=$BuildDate",
        "--label", "org.opencontainers.image.revision=$GitSha",
        "."
    )
    $null = Invoke-BuildCommand -Command $ContainerRuntime -Arguments $buildArgs
    if ($Latest) {
        $null = Invoke-BuildCommand -Command $ContainerRuntime -Arguments @("tag", $fullTag, "$IMAGE_PREFIX/${ImageName}:latest")
    }
    return $ImageName
}

function Push-Image {
    param([string]$ImageName)
    $fullTag = "$IMAGE_PREFIX/${ImageName}:$Version"
    Write-Host "`nPushing: $fullTag" -ForegroundColor Magenta
    $null = Invoke-BuildCommand -Command $ContainerRuntime -Arguments @("push", $fullTag)
    if ($Latest) {
        $null = Invoke-BuildCommand -Command $ContainerRuntime -Arguments @("push", "$IMAGE_PREFIX/${ImageName}:latest")
    }
}

Write-Host "============================================" -ForegroundColor Blue
Write-Host "Service Pack Release Dashboard - Image Builder" -ForegroundColor Blue
Write-Host "Runtime:     $ContainerRuntime"
Write-Host "Registry:    $REGISTRY"
Write-Host "Repository:  $REPO_PATH"
Write-Host "Version:     $Version"
Write-Host "Git SHA:     $GitSha"
Write-Host "============================================"

$ImagesBuilt = @()
foreach ($img in $IMAGES) {
    if (Test-Path $img.dockerfile) {
        $ImagesBuilt += Build-Image -ImageName $img.name -Dockerfile $img.dockerfile
    } else {
        Write-Host "Skipping $($img.name): $($img.dockerfile) not found" -ForegroundColor Yellow
    }
}

if ($Push -and $ImagesBuilt.Count -gt 0) {
    foreach ($img in $ImagesBuilt) { Push-Image -ImageName $img }
}

Write-Host "`nDone! Images built:" -ForegroundColor Green
foreach ($img in $ImagesBuilt) {
    Write-Host "  - $IMAGE_PREFIX/${img}:$Version"
    if ($Latest) { Write-Host "  - $IMAGE_PREFIX/${img}:latest" }
}
