// TypeScript generated by Copilot
import { useEffect, useState } from 'react';
import { getXlsxBytes, loadXLSX, WorkbookId } from '../data/workbook';

export interface WorkbookSheetState {
    rows: unknown[][];
    loading: boolean;
    error: string;
}

/** Reads one sheet of a shared workbook (planning by default) as raw rows (header: 1). */
export const useWorkbookSheet = (sheetName: string, refreshToken?: number, workbookId: WorkbookId = 'planning'): WorkbookSheetState => {
    const [state, setState] = useState<WorkbookSheetState>({ rows: [], loading: true, error: '' });

    useEffect(() => {
        let cancelled = false;
        setState({ rows: [], loading: true, error: '' });

        Promise.all([getXlsxBytes(workbookId), loadXLSX()])
            .then(([bytes, XLSX]) => {
                const workbook = XLSX.read(bytes, { type: 'array' });
                const sheet = workbook.Sheets[sheetName];
                if (!sheet) {
                    throw new Error(`Sheet "${sheetName}" not found. Available sheets: ${workbook.SheetNames.join(', ')}`);
                }
                const rows = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '' }) as unknown[][];
                if (!cancelled) setState({ rows, loading: false, error: '' });
            })
            .catch((err) => {
                if (!cancelled) setState({ rows: [], loading: false, error: err?.message || 'Failed to load spreadsheet data.' });
            });

        return () => { cancelled = true; };
    }, [sheetName, refreshToken, workbookId]);

    return state;
};
