// TypeScript generated by Copilot
import { useCallback, useEffect, useState } from 'react';
import { invalidateXlsxCache } from '../data/workbook';

// Keeps the "Refresh data" action visibly busy briefly, even on a fast fetch.
const MIN_REFRESH_FEEDBACK_MS = 400;

export interface WorkbookRefresh {
    refreshToken: number;
    refreshing: boolean;
    refresh: () => void;
}

/**
 * Shared refresh state for every view that reads the planning workbook.
 * Bumping refreshToken after invalidateXlsxCache() makes those views re-read
 * the workbook from its configured source without a full page reload.
 */
export const useWorkbookRefresh = (): WorkbookRefresh => {
    const [refreshToken, setRefreshToken] = useState(0);
    const [refreshing, setRefreshing] = useState(false);

    useEffect(() => {
        if (!refreshing) return undefined;
        const timer = window.setTimeout(() => setRefreshing(false), MIN_REFRESH_FEEDBACK_MS);
        return () => window.clearTimeout(timer);
    }, [refreshing]);

    const refresh = useCallback(() => {
        setRefreshing(true);
        invalidateXlsxCache();
        setRefreshToken((token) => token + 1);
    }, []);

    return { refreshToken, refreshing, refresh };
};
