// TypeScript generated by Copilot
import React from 'react';
import Dashboard from '../components/Dashboard';

// The page title lives in the sidebar brand and each view's page header.
const DashboardPage: React.FC = () => <Dashboard />;

export default DashboardPage;
