// TypeScript generated by Copilot
import React, { useState } from 'react';
import ServicePackOverview from './ServicePackOverview';
import ServicePackXlsxView from './ServicePackXlsxView';
import QuarterlyStatus from './QuarterlyStatus';
import IbSystemVersions from './IbSystemVersions';
import { useWorkbookRefresh } from '../hooks/useWorkbookRefresh';
import { CalendarIcon, DocumentIcon, ExternalIcon, RefreshIcon, ServerIcon, StatusIcon, StrategyIcon } from './icons';
import './Dashboard.css';

type ViewId = 'overview' | 'sp2026' | 'quarterly' | 'ibVersions' | 'guideline';

interface ViewConfig {
    id: ViewId;
    navLabel: string;
    title: string;
    subtitle: string;
    Icon: React.FC<{ className?: string }>;
    readsWorkbook?: boolean;
}

const VIEWS: Record<ViewId, ViewConfig> = {
    overview: {
        id: 'overview',
        navLabel: 'SP Strategy',
        title: 'Service pack release strategy',
        subtitle: 'Quarterly release cadence for each supported OS version, until its end of life.',
        Icon: StrategyIcon,
    },
    sp2026: {
        id: 'sp2026',
        navLabel: 'SP 2026 Plan',
        title: 'SP 2026 plan',
        subtitle: 'Service packs planned per OS version for each quarter of 2026.',
        Icon: CalendarIcon,
        readsWorkbook: true,
    },
    quarterly: {
        id: 'quarterly',
        navLabel: 'Quarterly Status',
        title: 'Quarterly status',
        subtitle: 'InCenter release schedule and phase-by-phase progress for each quarter.',
        Icon: StatusIcon,
        readsWorkbook: true,
    },
    ibVersions: {
        id: 'ibVersions',
        navLabel: 'IB System Versions',
        title: 'IB system release versions',
        subtitle: 'Installed-base systems and their product release, AS, OS and AWS versions, per Windows 10 OS version.',
        Icon: ServerIcon,
        readsWorkbook: true,
    },
    guideline: {
        id: 'guideline',
        navLabel: 'SP Guideline',
        title: 'SP guideline',
        subtitle: 'Service Pack Guideline, document 2009001390.',
        Icon: DocumentIcon,
    },
};

const NAV_SECTIONS: { heading: string; items: ViewId[] }[] = [
    { heading: 'Planning', items: ['overview', 'sp2026', 'quarterly'] },
    { heading: 'Reference', items: ['ibVersions', 'guideline'] },
];

const GUIDELINE_URL = '/api/sp-guideline-pdf';

const Dashboard: React.FC = () => {
    const [activeView, setActiveView] = useState<ViewId>('overview');
    const workbook = useWorkbookRefresh();
    const view = VIEWS[activeView];

    return (
        <div className="app-shell">
            <aside className="app-sidebar">
                <div className="brand">
                    <span className="brand__mark">SP</span>
                    <span className="brand__text">
                        <span className="brand__name">Service Pack</span>
                        <span className="brand__product">Release Dashboard</span>
                    </span>
                </div>
                <nav className="app-nav" aria-label="Dashboard sections">
                    {NAV_SECTIONS.map((section) => (
                        <div key={section.heading} className="app-nav__section">
                            <span className="app-nav__heading">{section.heading}</span>
                            {section.items.map((id) => {
                                const item = VIEWS[id];
                                const active = id === activeView;
                                return (
                                    <button
                                        key={id}
                                        type="button"
                                        className={active ? 'app-nav__item app-nav__item--active' : 'app-nav__item'}
                                        aria-current={active ? 'page' : undefined}
                                        onClick={() => setActiveView(id)}
                                    >
                                        <item.Icon />
                                        {item.navLabel}
                                    </button>
                                );
                            })}
                        </div>
                    ))}
                </nav>
            </aside>

            <main className="app-main">
                <header className="page-header">
                    <div className="page-header__text">
                        <h1 className="page-header__title">{view.title}</h1>
                        <p className="page-header__subtitle">{view.subtitle}</p>
                    </div>
                    <div className="page-header__actions">
                        {view.readsWorkbook && (
                            <>
                                <button
                                    type="button"
                                    className="button button--secondary"
                                    onClick={workbook.refresh}
                                    disabled={workbook.refreshing}
                                    title="Re-read the planning workbook from its configured source"
                                >
                                    <RefreshIcon className={workbook.refreshing ? 'icon--spin' : undefined} />
                                    {workbook.refreshing ? 'Refreshing…' : 'Refresh data'}
                                </button>
                            </>
                        )}
                        {activeView === 'guideline' && (
                            <a className="button button--secondary" href={GUIDELINE_URL} target="_blank" rel="noopener noreferrer">
                                <ExternalIcon />
                                Open in new tab
                            </a>
                        )}
                    </div>
                </header>

                <div className="page-body">
                    {activeView === 'overview' && <ServicePackOverview />}
                    {activeView === 'sp2026' && (
                        <ServicePackXlsxView
                            sheetName="service-pack-planning"
                            title="Planned service packs by quarter"
                            subtitle="One row per OS version. A dash means no service pack is planned for that quarter."
                            planYear={2026}
                            refreshToken={workbook.refreshToken}
                        />
                    )}
                    {activeView === 'quarterly' && <QuarterlyStatus refreshToken={workbook.refreshToken} />}
                    {activeView === 'ibVersions' && <IbSystemVersions refreshToken={workbook.refreshToken} />}
                    {activeView === 'guideline' && (
                        <section className="card document-card">
                            <object className="document-card__frame" data={GUIDELINE_URL} type="application/pdf">
                                <p className="state-message">
                                    Unable to display the PDF here.{' '}
                                    <a href={GUIDELINE_URL} target="_blank" rel="noopener noreferrer">Open the SP Guideline in a new tab</a>.
                                </p>
                            </object>
                        </section>
                    )}
                </div>
            </main>
        </div>
    );
};

export default Dashboard;
