// TypeScript generated by Copilot
import React, { useState } from 'react';
import { useWorkbookSheet } from '../hooks/useWorkbookSheet';
import { cellText } from './quarterSheet';
import { osToneClass } from './osTone';
import { LayersIcon, SearchIcon, StrategyIcon } from './icons';
import './IbSystemVersions.css';

const OS_TABS = [
    { id: '1607', label: 'Win10 1607', sheetName: 'Win10 1607' },
    { id: '1809', label: 'Win10 1809', sheetName: 'Win10 1809' },
    { id: '2021', label: 'Win10 2021', sheetName: 'Win10 2021' },
];

type ColumnKind = 'index' | 'system' | 'os' | 'aws' | 'version' | 'nc' | 'text';

const columnKind = (header: string): ColumnKind => {
    const key = header.toLowerCase().replace(/\s+/g, ' ');
    if (key.startsWith('sl')) return 'index';
    if (key === 'system type' || key === 'systen type') return 'system';
    if (key.includes('os version')) return 'os';
    if (key.includes('aws')) return 'aws';
    if (key.includes('as version')) return 'version';
    if (key.includes('6 nc') || key === '6nc') return 'nc';
    return 'text';
};

/** Removes non-breaking spaces and stray whitespace that the workbook cells carry. */
const clean = (value: unknown): string => cellText(value).replace(/\u00a0/g, ' ').replace(/[ \t]+/g, ' ').trim();

const splitLines = (value: string, extra?: RegExp): string[] =>
    value.split(extra ?? /\n/).map((part) => part.trim()).filter(Boolean);

const OS_SPLIT = /[\n,/]+/;

interface IbSheet {
    columns: { name: string; kind: ColumnKind; index: number }[];
    rows: string[][];
}

const parseSheet = (raw: unknown[][]): IbSheet => {
    const [headerRow = [], ...body] = raw;
    const rows = body.map((row) => headerRow.map((_, idx) => clean(row[idx])))
        .filter((row) => row.some((cell, idx) => idx > 0 && cell));
    const columns = headerRow
        .map((name, index) => ({ name: clean(name), kind: columnKind(clean(name)), index }))
        .filter((col) => col.name);
    return { columns, rows };
};

const Cell: React.FC<{ kind: ColumnKind; value: string }> = ({ kind, value }) => {
    if (!value) return <span className="cell-empty">—</span>;
    switch (kind) {
        case 'index':
            return <span className="ib-index">{value}</span>;
        case 'system':
            return <span className="tag tag--os">{value}</span>;
        case 'os':
            return (
                <span className="ib-stack">
                    {splitLines(value, OS_SPLIT).map((v) => <span key={v} className="ib-chip ib-chip--os">{v}</span>)}
                </span>
            );
        case 'aws':
            return (
                <span className="ib-stack">
                    {splitLines(value).map((line) => (/^remarks?\s*:/i.test(line)
                        ? <span key={line} className="ib-remark">{line.replace(/^remarks?\s*:\s*/i, '')}</span>
                        : <span key={line} className="ib-chip">{line}</span>))}
                </span>
            );
        case 'version':
        case 'nc':
            return (
                <span className="ib-stack">
                    {splitLines(value).map((v) => <span key={v} className="ib-mono">{v}</span>)}
                </span>
            );
        default:
            return <span className="ib-text"><BreakableText value={value} /></span>;
    }
};

/** Lets underscore-joined names (e.g. "Philips_Radiography_7000_M_R1.0.2") wrap after each underscore. */
const BreakableText: React.FC<{ value: string }> = ({ value }) => (
    <>
        {value.split('_').map((part, idx, parts) => (
            <React.Fragment key={idx}>{part}{idx < parts.length - 1 && <>_<wbr /></>}</React.Fragment>
        ))}
    </>
);

const summarize = (sheet: IbSheet) => {
    const versionCol = sheet.columns.find((c) => c.kind === 'version');
    const versions = versionCol
        ? sheet.rows.flatMap((row) => splitLines(row[versionCol.index]))
        : [];
    return { releases: sheet.rows.length, softwareVersions: new Set(versions).size };
};

interface Props {
    refreshToken?: number;
}

const IbSystemVersions: React.FC<Props> = ({ refreshToken }) => {
    const [activeId, setActiveId] = useState(OS_TABS[0].id);
    const [query, setQuery] = useState('');

    // One read per OS sheet; the workbook bytes are fetched once and cached.
    const sheets = {
        '1607': useWorkbookSheet(OS_TABS[0].sheetName, refreshToken, 'ibSystemVersions'),
        '1809': useWorkbookSheet(OS_TABS[1].sheetName, refreshToken, 'ibSystemVersions'),
        '2021': useWorkbookSheet(OS_TABS[2].sheetName, refreshToken, 'ibSystemVersions'),
    } as Record<string, ReturnType<typeof useWorkbookSheet>>;

    const parsed = Object.fromEntries(
        Object.entries(sheets).map(([id, sheetState]) => [id, parseSheet(sheetState.rows)]),
    ) as Record<string, IbSheet>;

    const active = OS_TABS.find((tab) => tab.id === activeId) ?? OS_TABS[0];
    const state = sheets[active.id];
    const sheet = parsed[active.id];
    const summary = summarize(sheet);

    const needle = query.trim().toLowerCase();
    const visibleRows = needle
        ? sheet.rows.filter((row) => row.some((cell) => cell.toLowerCase().includes(needle)))
        : sheet.rows;

    return (
        <div className={`page-stack ${osToneClass(active.id)}`}>
            <div className="segmented segmented--os" role="tablist" aria-label="Select OS version">
                {OS_TABS.map((tab) => (
                    <button
                        key={tab.id}
                        type="button"
                        role="tab"
                        aria-selected={tab.id === activeId}
                        className={`segmented__item ${osToneClass(tab.id)}${tab.id === activeId ? ' segmented__item--active' : ''}`}
                        onClick={() => setActiveId(tab.id)}
                    >
                        {tab.label}
                        {!sheets[tab.id].loading && <span className="segmented__count">{parsed[tab.id].rows.length}</span>}
                    </button>
                ))}
            </div>

            {!state.loading && !state.error && (
                <div className="kpi-grid kpi-grid--two">
                    <div className="card kpi ib-kpi">
                        <span className="kpi__icon"><LayersIcon /></span>
                        <span className="kpi__label">Product releases</span>
                        <span className="kpi__value">{summary.releases}</span>
                        <span className="kpi__hint">Installed-base releases on {active.label}</span>
                    </div>
                    <div className="card kpi ib-kpi">
                        <span className="kpi__icon"><StrategyIcon /></span>
                        <span className="kpi__label">Software versions</span>
                        <span className="kpi__value">{summary.softwareVersions}</span>
                        <span className="kpi__hint">Distinct AS versions on {active.label}</span>
                    </div>
                </div>
            )}

            <section className="card">
                <div className="card__header">
                    <div>
                        <h2 className="card__title">{active.label} system releases</h2>
                        <p className="card__subtitle">System type, product release, AS and OS version, AWS type and 6NC per release.</p>
                    </div>
                    <label className="search-field">
                        <SearchIcon />
                        <input
                            type="search"
                            placeholder="Filter releases…"
                            value={query}
                            onChange={(e) => setQuery(e.target.value)}
                            aria-label={`Filter ${active.label} releases`}
                        />
                    </label>
                </div>

                {state.loading && <p className="state-message">Loading {active.label} systems…</p>}
                {!state.loading && state.error && <p className="state-message state-message--error">{state.error}</p>}
                {!state.loading && !state.error && visibleRows.length === 0 && (
                    <p className="state-message">{needle ? `No releases match “${query.trim()}”.` : `No systems found in “${active.sheetName}”.`}</p>
                )}
                {!state.loading && !state.error && visibleRows.length > 0 && (
                    <div className="table-scroll">
                        <table className="data-table data-table--ib">
                            <thead>
                                <tr>
                                    {sheet.columns.map((col) => (
                                        <th key={col.index} scope="col" className={`ib-col--${col.kind}`}>
                                            {col.kind === 'index' ? '#' : col.name}
                                        </th>
                                    ))}
                                </tr>
                            </thead>
                            <tbody>
                                {visibleRows.map((row, rowIdx) => (
                                    <tr key={`${row[0]}-${rowIdx}`}>
                                        {sheet.columns.map((col) => (
                                            <td key={col.index} className={`ib-col--${col.kind}`}>
                                                <Cell kind={col.kind} value={row[col.index]} />
                                            </td>
                                        ))}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
                {needle && visibleRows.length > 0 && (
                    <p className="card__footnote ib-footnote">Showing {visibleRows.length} of {sheet.rows.length} releases.</p>
                )}
            </section>
        </div>
    );
};

export default IbSystemVersions;
