// TypeScript generated by Copilot
import React from 'react';

type IconProps = { className?: string };

const Svg: React.FC<IconProps & { children: React.ReactNode }> = ({ className, children }) => (
    <svg
        className={className ? `icon ${className}` : 'icon'}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth={1.8}
        strokeLinecap="round"
        strokeLinejoin="round"
        aria-hidden="true"
    >
        {children}
    </svg>
);

export const StrategyIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="M4 19V9" /><path d="M10 19V5" /><path d="M16 19v-7" /><path d="M22 19H2" /></Svg>
);

export const CalendarIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><rect x="3" y="4.5" width="18" height="16" rx="2.5" /><path d="M3 9.5h18" /><path d="M8 2.5v4" /><path d="M16 2.5v4" /></Svg>
);

export const StatusIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="M3 12h4l3 7 4-14 3 7h4" /></Svg>
);

export const DocumentIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="M14 2.5H6.5a2 2 0 0 0-2 2v15a2 2 0 0 0 2 2h11a2 2 0 0 0 2-2V8z" /><path d="M14 2.5V8h5.5" /><path d="M8.5 13h7" /><path d="M8.5 17h5" /></Svg>
);

export const RefreshIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="M20 11a8 8 0 1 0-2.3 5.7" /><path d="M20 4v7h-7" /></Svg>
);

export const ExternalIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="M14 4h6v6" /><path d="M20 4 11 13" /><path d="M18 14v5a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 4 19V7.5A1.5 1.5 0 0 1 5.5 6H10" /></Svg>
);

export const CheckIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="m5 12.5 4.5 4.5L19 7.5" /></Svg>
);

export const CycleIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="M20 12a8 8 0 0 1-13.7 5.6" /><path d="M4 12a8 8 0 0 1 13.7-5.6" /><path d="M18 2.5v4.2h-4.2" /><path d="M6 21.5v-4.2h4.2" /></Svg>
);

export const MonitorIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><rect x="2.5" y="3.5" width="19" height="13" rx="2" /><path d="M8 21h8" /><path d="M12 16.5V21" /></Svg>
);

export const HourglassIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="M6.5 2.5h11" /><path d="M6.5 21.5h11" /><path d="M8 2.5v3.5l4 6-4 6v3.5" /><path d="M16 2.5v3.5l-4 6 4 6v3.5" /></Svg>
);

export const LayersIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><path d="m12 3 9 5-9 5-9-5z" /><path d="m3 13 9 5 9-5" /></Svg>
);

export const ServerIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><rect x="3" y="3.5" width="18" height="7" rx="2" /><rect x="3" y="13.5" width="18" height="7" rx="2" /><path d="M7 7h.01" /><path d="M7 17h.01" /></Svg>
);

export const SearchIcon: React.FC<IconProps> = (p) => (
    <Svg {...p}><circle cx="11" cy="11" r="7" /><path d="m20.5 20.5-4.5-4.5" /></Svg>
);
