// TypeScript generated by Copilot
// One colour per OS version, shared by every view so an OS reads the same
// colour on the strategy, plan and quarterly pages.

export type OsTone = 'blue' | 'violet' | 'teal' | 'indigo' | 'slate';

const TONE_BY_VERSION: [RegExp, OsTone][] = [
    [/\b1607\b/, 'blue'],
    [/\b1809\b/, 'violet'],
    [/\b2021\b/, 'teal'],
    [/\b2024\b|windows\s*11/i, 'indigo'],
];

export const osTone = (name: string): OsTone =>
    TONE_BY_VERSION.find(([pattern]) => pattern.test(name))?.[1] ?? 'slate';

export const osToneClass = (name: string): string => `os-tone--${osTone(name)}`;
