// TypeScript generated by Copilot
// Shared parser for the "SP Plan - Qn" sheets. Each sheet repeats a
// (status row, plan-week row) pair per product, may repeat its "Product"
// header row mid-sheet with extra columns, and may contain blank separator
// rows or plan rows whose first cell is blank instead of "Plan".

const HEADER_LABEL = 'product';
const PLAN_LABEL = 'plan';

export const cellText = (value: unknown): string => String(value ?? '').trim();

export interface QuarterProduct {
    product: string;
    statusRow: string[];
    planRows: string[][];
}

export interface QuarterSheet {
    /** Index-aligned with sheet columns; '' where a column has no header name. Index 0 is the product column. */
    columnNames: string[];
    products: QuarterProduct[];
}

export const parseQuarterSheet = (rows: unknown[][]): QuarterSheet => {
    const width = rows.reduce((max, row) => Math.max(max, row.length), 0);
    const columnNames: string[] = new Array(width).fill('');
    const isHeaderRow = (row: unknown[]) => cellText(row[0]).toLowerCase() === HEADER_LABEL;
    const hasHeaderRow = rows.some(isHeaderRow);
    const headerRows = hasHeaderRow ? rows.filter(isHeaderRow) : rows.slice(0, 1);

    // First non-blank name seen per column wins, so a later, wider header
    // row can name columns (e.g. "Actual") the first header row lacked.
    headerRows.forEach((row) => {
        row.forEach((raw, idx) => {
            const name = cellText(raw);
            if (idx > 0 && name && !columnNames[idx]) columnNames[idx] = name;
        });
    });

    const products: QuarterProduct[] = [];
    let current: QuarterProduct | null = null;
    const toCells = (row: unknown[]) => Array.from({ length: width }, (_, idx) => cellText(row[idx]));

    rows.forEach((row, rowIdx) => {
        if (!hasHeaderRow && rowIdx === 0) return;
        if (isHeaderRow(row)) return;

        const cells = toCells(row);
        const label = cells[0];
        const rowHasData = cells.slice(1).some((cell) => cell !== '');
        if (!label && !rowHasData) return;

        if (label && label.toLowerCase() !== PLAN_LABEL) {
            current = { product: label, statusRow: cells, planRows: [] };
            products.push(current);
            return;
        }
        if (current) current.planRows.push(cells);
    });

    return { columnNames, products };
};

/** Last non-blank plan value for a column across the product's plan rows. */
export const planValue = (product: QuarterProduct, columnIndex: number): string => {
    for (let i = product.planRows.length - 1; i >= 0; i -= 1) {
        const value = product.planRows[i][columnIndex];
        if (value) return value;
    }
    return '';
};

export type StatusTone = 'completed' | 'progress' | 'pending' | 'blocked' | 'neutral';

export const statusTone = (value: string): StatusTone => {
    const key = value.toLowerCase().replace(/[\s_-]+/g, '');
    if (key === 'completed' || key === 'done') return 'completed';
    if (key === 'inprogress' || key === 'ongoing') return 'progress';
    if (key === 'yettostart' || key === 'notstarted' || key === 'pending') return 'pending';
    if (key === 'blocked') return 'blocked';
    return 'neutral';
};

const STATUS_LABEL: Record<Exclude<StatusTone, 'neutral'>, string> = {
    completed: 'Completed',
    progress: 'In progress',
    pending: 'Yet to start',
    blocked: 'Blocked',
};

/** Normalises spreadsheet spelling variants ("Inprogress", "yet to start") for display. */
export const statusLabel = (value: string): string => {
    const tone = statusTone(value);
    return tone === 'neutral' ? value : STATUS_LABEL[tone];
};

/** Displays plan weeks in one form ("Wk 24 '26") whatever spelling the workbook uses. */
export const formatWeekText = (value: string): string => {
    const m = /^wk\s*(\d{1,2})\s*'\s*(\d{4})$/i.exec(value);
    return m ? `Wk ${parseInt(m[1], 10)} '${m[2].slice(-2)}` : value;
};
