// TypeScript generated by Copilot
import React, { useEffect, useState } from 'react';
import QuarterlyScheduleChart from './QuarterlyScheduleChart';
import ServicePackXlsxView, { invalidateXlsxCache, getXlsxBytes, getXlsxFetchMeta } from './ServicePackXlsxView';

const QUARTERS: { id: string; label: string; sheetName: string }[] = [
    { id: 'q1', label: 'Q1', sheetName: 'SP Plan - Q1' },
    { id: 'q2', label: 'Q2', sheetName: 'SP Plan - Q2' },
    { id: 'q3', label: 'Q3', sheetName: 'SP Plan - Q3' },
    { id: 'q4', label: 'Q4', sheetName: 'SP Plan Q4' },
];

const SOURCE_LABEL: Record<string, string> = {
    external: 'live network share',
    bundled: 'bundled snapshot (no live share configured)',
    'bundled-fallback': 'bundled snapshot (live share was unreachable)',
};

const QuarterlyStatus: React.FC = () => {
    const [activeQuarter, setActiveQuarter] = useState<string>(QUARTERS[0].id);
    const [refreshToken, setRefreshToken] = useState(0);
    const [refreshing, setRefreshing] = useState(false);
    const [, setMetaTick] = useState(0); // forces a re-render once getXlsxFetchMeta() has real data
    const current = QUARTERS.find((q) => q.id === activeQuarter) ?? QUARTERS[0];

    // After editing the source workbook on the network share, this re-fetches
    // it without requiring a full browser reload — see invalidateXlsxCache().
    const handleRefresh = async () => {
        setRefreshing(true);
        invalidateXlsxCache();
        setRefreshToken((t) => t + 1);
        // Brief delay so the button's "Refreshing…" state is visible even on a fast fetch.
        setTimeout(() => setRefreshing(false), 400);
    };

    const meta = getXlsxFetchMeta();

    // getXlsxFetchMeta() only updates after a fetch resolves inside the child
    // components below; re-render once that happens so the "Data source"
    // note reflects the real fetch, including on first mount (not just after
    // some other state change forces a re-render).
    useEffect(() => {
        let cancelled = false;
        getXlsxBytes()
            .then(() => { if (!cancelled) setMetaTick((t) => t + 1); })
            .catch(() => { /* surfaced by the child components' own error state */ });
        return () => { cancelled = true; };
    }, [refreshToken]);

    return (
        <div className="quarterly-status">
            <div className="quarterly-status__toolbar">
                <div className="quarter-tabs" role="tablist" aria-label="Select quarter">
                    {QUARTERS.map((q) => (
                        <button
                            key={q.id}
                            type="button"
                            role="tab"
                            aria-selected={q.id === activeQuarter}
                            className={q.id === activeQuarter ? 'quarter-tab quarter-tab--active' : 'quarter-tab'}
                            onClick={() => setActiveQuarter(q.id)}
                        >
                            {q.label}
                        </button>
                    ))}
                </div>
                <button
                    type="button"
                    className="refresh-data-button"
                    onClick={handleRefresh}
                    disabled={refreshing}
                    title="Re-read the planning workbook from its configured source"
                >
                    {refreshing ? 'Refreshing…' : '↻ Refresh data'}
                </button>
            </div>
            {meta && (
                <p className="data-source-note">
                    Data source: {SOURCE_LABEL[meta.source] || meta.source} · last loaded {meta.fetchedAt.toLocaleTimeString()}
                </p>
            )}
            <QuarterlyScheduleChart sheetName={current.sheetName} title={`${current.label} Schedule`} refreshToken={refreshToken} />
            <ServicePackXlsxView sheetName={current.sheetName} title={`${current.label} Status`} refreshToken={refreshToken} />
        </div>
    );
};

export default QuarterlyStatus;
