// TypeScript generated by Copilot
import React, { useMemo } from 'react';
import { useWorkbookSheet } from '../hooks/useWorkbookSheet';
import { formatWeekText, parseQuarterSheet, planValue, QuarterProduct, statusLabel, statusTone, StatusTone } from './quarterSheet';
import { osToneClass } from './osTone';

const LEGEND: { tone: StatusTone; label: string }[] = [
    { tone: 'completed', label: 'Completed' },
    { tone: 'progress', label: 'In progress' },
    { tone: 'pending', label: 'Yet to start' },
    { tone: 'blocked', label: 'Blocked' },
];

const SERVICE_PACK_SUFFIX = /^(.*?)\s+(SP\s*\d+)$/i;

const isActualColumn = (name: string) => name.toLowerCase() === 'actual';

const ProductLabel: React.FC<{ name: string }> = ({ name }) => {
    const match = SERVICE_PACK_SUFFIX.exec(name);
    return (
        <span className={`os-label ${osToneClass(name)}`}>
            <span className="os-swatch" aria-hidden="true" />
            <span className="product-label">
                <span className="product-label__os">{match ? match[1] : name}</span>
                {match && <span className="tag tag--os">{match[2].replace(/\s+/g, '')}</span>}
            </span>
        </span>
    );
};

/** Share of a product's tracked phases that are completed. */
const PhaseProgress: React.FC<{ product: QuarterProduct; columns: { index: number }[] }> = ({ product, columns }) => {
    const tones = columns
        .map((column) => statusTone(product.statusRow[column.index] ?? ''))
        .filter((tone) => tone !== 'neutral');
    if (tones.length === 0) return null;
    const done = tones.filter((tone) => tone === 'completed').length;
    const percent = Math.round((done / tones.length) * 100);
    return (
        <span className="phase-progress" title={`${done} of ${tones.length} phases completed`}>
            <span className="phase-progress__track">
                <span
                    className={percent === 100 ? 'phase-progress__bar phase-progress__bar--done' : 'phase-progress__bar'}
                    style={{ width: `${percent}%` }}
                />
            </span>
            <span className="phase-progress__text">{done}/{tones.length} phases</span>
        </span>
    );
};

export const StatusBadge: React.FC<{ value: string }> = ({ value }) => (
    <span className={`status-badge status-badge--${statusTone(value)}`}>
        <span className="status-badge__dot" />
        {statusLabel(value)}
    </span>
);

const PhaseCell: React.FC<{ product: QuarterProduct; columnIndex: number }> = ({ product, columnIndex }) => {
    const status = product.statusRow[columnIndex];
    const week = planValue(product, columnIndex);
    if (!status && !week) return <span className="cell-empty">—</span>;

    const isStatus = status && statusTone(status) !== 'neutral';
    return (
        <span className="phase-cell">
            {isStatus && <StatusBadge value={status} />}
            {status && !isStatus && <span className="phase-cell__text">{formatWeekText(status)}</span>}
            {week && <span className="phase-cell__week">{formatWeekText(week)}</span>}
        </span>
    );
};

interface Props {
    sheetName: string;
    title: string;
    refreshToken?: number;
}

const QuarterStatusTable: React.FC<Props> = ({ sheetName, title, refreshToken }) => {
    const { rows, loading, error } = useWorkbookSheet(sheetName, refreshToken);
    const sheet = useMemo(() => parseQuarterSheet(rows), [rows]);

    // Keep a column when it is named or holds data for any product, so
    // unnamed trailing spreadsheet columns don't render as empty headers.
    const columns = useMemo(() => sheet.columnNames
        .map((name, index) => ({ name, index }))
        .filter(({ name, index }) => index > 0 && (name || sheet.products.some((p) => p.statusRow[index] || planValue(p, index)))),
    [sheet]);

    return (
        <section className="card">
            <div className="card__header">
                <div>
                    <h2 className="card__title">{title}</h2>
                    <p className="card__subtitle">Status of each phase, with its planned week beneath.</p>
                </div>
                <ul className="legend" aria-label="Status legend">
                    {LEGEND.map((item) => (
                        <li key={item.tone} className="legend__item">
                            <span className={`legend__swatch legend__swatch--${item.tone}`} />
                            {item.label}
                        </li>
                    ))}
                </ul>
            </div>

            {loading && <p className="state-message">Loading {title.toLowerCase()}…</p>}
            {!loading && error && <p className="state-message state-message--error">{error}</p>}
            {!loading && !error && sheet.products.length === 0 && (
                <p className="state-message">No products found in “{sheetName}”.</p>
            )}
            {!loading && !error && sheet.products.length > 0 && (
                <div className="table-scroll">
                    <table className="data-table data-table--status">
                        <thead>
                            <tr>
                                <th scope="col" className="data-table__sticky">Product</th>
                                {columns.map((column) => (
                                    <th key={column.index} scope="col" className={isActualColumn(column.name) ? 'data-table__highlight' : undefined}>
                                        {column.name}
                                    </th>
                                ))}
                            </tr>
                        </thead>
                        <tbody>
                            {sheet.products.map((product, rowIndex) => (
                                <tr key={`${product.product}-${rowIndex}`}>
                                    <th scope="row" className="data-table__sticky">
                                        <ProductLabel name={product.product} />
                                        <PhaseProgress product={product} columns={columns} />
                                    </th>
                                    {columns.map((column) => (
                                        <td key={column.index} className={isActualColumn(column.name) ? 'data-table__highlight' : undefined}>
                                            <PhaseCell product={product} columnIndex={column.index} />
                                        </td>
                                    ))}
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </section>
    );
};

export default QuarterStatusTable;
