// TypeScript generated by Copilot
import React, { useState } from 'react';
import QuarterlyScheduleChart from './QuarterlyScheduleChart';
import QuarterStatusTable from './QuarterStatusTable';

const QUARTERS: { id: string; label: string; sheetName: string }[] = [
    { id: 'q1', label: 'Q1', sheetName: 'SP Plan - Q1' },
    { id: 'q2', label: 'Q2', sheetName: 'SP Plan - Q2' },
    { id: 'q3', label: 'Q3', sheetName: 'SP Plan - Q3' },
    { id: 'q4', label: 'Q4', sheetName: 'SP Plan Q4' },
];

interface Props {
    /** Bumped by the dashboard's "Refresh data" action to re-read the workbook. */
    refreshToken: number;
}

const QuarterlyStatus: React.FC<Props> = ({ refreshToken }) => {
    const [activeQuarter, setActiveQuarter] = useState<string>(QUARTERS[0].id);
    const current = QUARTERS.find((q) => q.id === activeQuarter) ?? QUARTERS[0];

    return (
        <div className="quarterly-status">
            <div className="segmented" role="tablist" aria-label="Select quarter">
                {QUARTERS.map((q) => (
                    <button
                        key={q.id}
                        type="button"
                        role="tab"
                        aria-selected={q.id === activeQuarter}
                        className={`segmented__item plan-quarter--${q.id}${q.id === activeQuarter ? ' segmented__item--active' : ''}`}
                        onClick={() => setActiveQuarter(q.id)}
                    >
                        {q.label}
                    </button>
                ))}
            </div>
            <QuarterlyScheduleChart sheetName={current.sheetName} title={`${current.label} InCenter release schedule`} refreshToken={refreshToken} />
            <QuarterStatusTable sheetName={current.sheetName} title={`${current.label} phase status`} refreshToken={refreshToken} />
        </div>
    );
};

export default QuarterlyStatus;
