// TypeScript generated by Copilot
import React, { useState } from 'react';
import QuarterlyScheduleChart from './QuarterlyScheduleChart';
import ServicePackXlsxView from './ServicePackXlsxView';

const QUARTERS: { id: string; label: string; sheetName: string }[] = [
    { id: 'q1', label: 'Q1', sheetName: 'SP Plan - Q1' },
    { id: 'q2', label: 'Q2', sheetName: 'SP Plan - Q2' },
    { id: 'q3', label: 'Q3', sheetName: 'SP Plan - Q3' },
    { id: 'q4', label: 'Q4', sheetName: 'SP Plan Q4' },
];

const QuarterlyStatus: React.FC = () => {
    const [activeQuarter, setActiveQuarter] = useState<string>(QUARTERS[0].id);
    const current = QUARTERS.find((q) => q.id === activeQuarter) ?? QUARTERS[0];

    return (
        <div className="quarterly-status">
            <div className="quarter-tabs" role="tablist" aria-label="Select quarter">
                {QUARTERS.map((q) => (
                    <button
                        key={q.id}
                        type="button"
                        role="tab"
                        aria-selected={q.id === activeQuarter}
                        className={q.id === activeQuarter ? 'quarter-tab quarter-tab--active' : 'quarter-tab'}
                        onClick={() => setActiveQuarter(q.id)}
                    >
                        {q.label}
                    </button>
                ))}
            </div>
            <QuarterlyScheduleChart sheetName={current.sheetName} title={`${current.label} Schedule`} />
            <ServicePackXlsxView sheetName={current.sheetName} title={`${current.label} Status`} />
        </div>
    );
};

export default QuarterlyStatus;
