// TypeScript generated by Copilot
import React, { useMemo } from 'react';
import { Line } from 'react-chartjs-2';
import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Tooltip,
} from 'chart.js';
import { useWorkbookSheet } from '../hooks/useWorkbookSheet';
import { parseQuarterSheet } from './quarterSheet';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Tooltip);

// Plots only the InCenter release milestone (Planned vs. Actual) per OS
// version as a dumbbell: a hollow ring for Planned and a colour-coded dot for
// Actual, joined by a connector, with a dotted stem down to the x axis. The
// other phases remain visible in the phase status table below the chart.
// Columns are discovered from each sheet's header row, since the Q1-Q4
// sheets do not share one fixed layout (only some have an "Actual" column).
const INCENTER_PHASE = 'InCenter release';
const ACTUAL_LABEL = 'actual';

const FONT_FAMILY = "'Segoe UI', system-ui, -apple-system, sans-serif";
const PLANNED_COLOR = '#64748b';
const LATE_COLOR = '#e11d48';
const ON_TIME_COLOR = '#0f9f8f';
const UNKNOWN_COMPARISON_COLOR = '#94a3b8';
const AXIS_TEXT_COLOR = '#64748b';
const GRID_COLOR = '#eef2f7';
const STEM_COLOR = '#cbd5e1';

ChartJS.defaults.font.family = FONT_FAMILY;

// Earliest year observed in the planning data — turns "Wk NN'YYYY" labels
// into one continuous, sortable number for the Y axis.
const BASE_YEAR = 2025;

interface ProductSchedule {
    product: string;
    plannedWeekIndex: number | null;
    actualWeekIndex: number | null;
}

interface QuarterSchedule {
    products: ProductSchedule[];
    hasActualColumn: boolean;
}

const parseWeekLabel = (label: string): number | null => {
    const m = /wk\s*(\d{1,2})\s*'\s*(\d{4})/i.exec(label);
    if (!m) return null; // e.g. a bare "2025" placeholder — not a week
    return (parseInt(m[2], 10) - BASE_YEAR) * 52 + parseInt(m[1], 10);
};

const lastWeekIn = (planRows: string[][], columnIndex: number): number | null => {
    let week: number | null = null;
    if (columnIndex < 0) return week;
    planRows.forEach((row) => {
        const parsed = row[columnIndex] ? parseWeekLabel(row[columnIndex]) : null;
        if (parsed !== null) week = parsed;
    });
    return week;
};

const toSchedule = (rows: unknown[][]): QuarterSchedule => {
    const { columnNames, products } = parseQuarterSheet(rows);
    const incenterIndex = columnNames.indexOf(INCENTER_PHASE);
    const actualIndex = columnNames.findIndex((name) => name.toLowerCase() === ACTUAL_LABEL);
    return {
        hasActualColumn: actualIndex >= 0,
        products: products.map((p) => ({
            product: p.product,
            plannedWeekIndex: lastWeekIn(p.planRows, incenterIndex),
            actualWeekIndex: lastWeekIn(p.planRows, actualIndex),
        })),
    };
};

const formatWeekIndex = (weekIndex: number): string => {
    const zeroBased = weekIndex - 1;
    const year = BASE_YEAR + Math.floor(zeroBased / 52);
    const week = (zeroBased % 52) + 1;
    return `Wk ${week} '${String(year).slice(-2)}`;
};

const comparisonColor = (p: ProductSchedule): string => {
    if (p.actualWeekIndex === null) return 'transparent';
    if (p.plannedWeekIndex === null) return UNKNOWN_COMPARISON_COLOR;
    return p.actualWeekIndex > p.plannedWeekIndex ? LATE_COLOR : ON_TIME_COLOR;
};

const summarize = (schedule: QuarterSchedule) => {
    const compared = schedule.products.filter((p) => p.actualWeekIndex !== null && p.plannedWeekIndex !== null);
    const late = compared.filter((p) => p.actualWeekIndex! > p.plannedWeekIndex!).length;
    return {
        total: schedule.products.length,
        onTime: compared.length - late,
        late,
    };
};

interface Props {
    sheetName: string;
    title: string;
    /** Bump this (e.g. a counter) to force a re-fetch after invalidateXlsxCache(). */
    refreshToken?: number;
}

const QuarterlyScheduleChart: React.FC<Props> = ({ sheetName, title, refreshToken }) => {
    const { rows, loading, error } = useWorkbookSheet(sheetName, refreshToken);
    const schedule = useMemo(() => toSchedule(rows), [rows]);
    const summary = useMemo(() => summarize(schedule), [schedule]);

    // Only real observed week values become Y-axis ticks, so every tick
    // reads as a genuine "Wk NN 'YY" label.
    const tickValues = useMemo(() => {
        const all = new Set<number>();
        schedule.products.forEach((p) => {
            if (p.plannedWeekIndex !== null) all.add(p.plannedWeekIndex);
            if (p.actualWeekIndex !== null) all.add(p.actualWeekIndex);
        });
        return Array.from(all).sort((a, b) => a - b);
    }, [schedule]);

    const chartData = useMemo(() => {
        const { products, hasActualColumn } = schedule;
        const pointStyle = { showLine: false, pointRadius: 5.5, pointHoverRadius: 8 };
        const plannedDataset = {
            ...pointStyle,
            label: 'Planned',
            data: products.map((p) => p.plannedWeekIndex),
            pointBackgroundColor: '#ffffff',
            pointBorderColor: PLANNED_COLOR,
            pointBorderWidth: 2.5,
            order: 1,
        };
        const datasets: any[] = [plannedDataset];
        if (hasActualColumn) {
            datasets.push({
                ...pointStyle,
                label: 'Actual',
                data: products.map((p) => p.actualWeekIndex),
                pointBackgroundColor: products.map(comparisonColor),
                pointBorderColor: '#ffffff',
                pointBorderWidth: 2,
                order: 0,
            });
        }
        return { labels: products.map((p) => p.product), datasets };
    }, [schedule]);

    // Chart-local plugin: dotted stems, planned→actual connectors, and week
    // labels beside each point. Registered per instance, so it never affects
    // other charts.
    const dumbbellPlugin = useMemo(() => ({
        id: 'schedule-chart-dumbbell',
        beforeDatasetsDraw(chart: any) {
            const { ctx, chartArea } = chart;
            const plannedMeta = chart.getDatasetMeta(0);
            const actualMeta = chart.data.datasets.length > 1 ? chart.getDatasetMeta(1) : null;

            ctx.save();
            ctx.setLineDash([3, 4]);
            ctx.lineWidth = 1;
            ctx.strokeStyle = STEM_COLOR;
            schedule.products.forEach((p, i) => {
                const plannedEl = p.plannedWeekIndex !== null ? plannedMeta.data[i] : null;
                const actualEl = actualMeta && p.actualWeekIndex !== null ? actualMeta.data[i] : null;
                const topEl = [plannedEl, actualEl].filter(Boolean).sort((a: any, b: any) => a.y - b.y)[0];
                if (!topEl) return;
                ctx.beginPath();
                ctx.moveTo(topEl.x, chartArea.bottom);
                ctx.lineTo(topEl.x, topEl.y);
                ctx.stroke();
            });
            ctx.restore();

            if (!actualMeta) return;
            ctx.save();
            ctx.lineWidth = 4;
            ctx.lineCap = 'round';
            ctx.globalAlpha = 0.3;
            schedule.products.forEach((p, i) => {
                if (p.actualWeekIndex === null || p.plannedWeekIndex === null) return;
                const from = plannedMeta.data[i];
                const to = actualMeta.data[i];
                if (!from || !to) return;
                ctx.beginPath();
                ctx.moveTo(from.x, from.y);
                ctx.lineTo(to.x, to.y);
                ctx.strokeStyle = comparisonColor(p);
                ctx.stroke();
            });
            ctx.restore();
        },
        afterDatasetsDraw(chart: any) {
            const { ctx } = chart;
            const plannedMeta = chart.getDatasetMeta(0);
            const actualMeta = chart.data.datasets.length > 1 ? chart.getDatasetMeta(1) : null;
            ctx.save();
            ctx.font = `600 11px ${FONT_FAMILY}`;
            ctx.textAlign = 'center';
            const label = (text: string, color: string, x: number, y: number) => {
                ctx.fillStyle = color;
                ctx.fillText(text, x, y);
            };
            schedule.products.forEach((p, i) => {
                const plannedEl = p.plannedWeekIndex !== null ? plannedMeta.data[i] : null;
                const actualEl = actualMeta && p.actualWeekIndex !== null ? actualMeta.data[i] : null;
                const actualColor = comparisonColor(p) === 'transparent' ? '#334155' : comparisonColor(p);
                const planText = plannedEl ? `Plan ${formatWeekIndex(p.plannedWeekIndex!)}` : '';
                const actualText = actualEl ? `Actual ${formatWeekIndex(p.actualWeekIndex!)}` : '';

                if (plannedEl && actualEl) {
                    // Label each point on the side facing away from the other,
                    // so labels never overlap each other or the connector.
                    const plannedAbove = plannedEl.y <= actualEl.y - 4;
                    const coincide = Math.abs(plannedEl.y - actualEl.y) < 4;
                    label(actualText, actualColor, actualEl.x, coincide || !plannedAbove ? actualEl.y - 15 : actualEl.y + 24);
                    label(planText, PLANNED_COLOR, plannedEl.x, coincide || !plannedAbove ? plannedEl.y + 24 : plannedEl.y - 15);
                } else if (plannedEl) {
                    label(planText, PLANNED_COLOR, plannedEl.x, plannedEl.y - 15);
                } else if (actualEl) {
                    label(actualText, actualColor, actualEl.x, actualEl.y - 15);
                }
            });
            ctx.restore();
        },
    }), [schedule]);

    const hasWeeks = tickValues.length > 0;

    return (
        <section className="card schedule-chart">
            <div className="card__header">
                <div>
                    <h2 className="card__title">{title}</h2>
                    <p className="card__subtitle">Planned vs. actual InCenter release week, by OS version.</p>
                </div>
                {!loading && !error && summary.total > 0 && (
                    <dl className="stat-row">
                        <div className="stat"><dt>Releases</dt><dd>{summary.total}</dd></div>
                        {schedule.hasActualColumn && (
                            <>
                                <div className="stat stat--positive"><dt>On time</dt><dd>{summary.onTime}</dd></div>
                                <div className="stat stat--negative"><dt>Late</dt><dd>{summary.late}</dd></div>
                            </>
                        )}
                    </dl>
                )}
            </div>

            {loading && <p className="state-message">Loading schedule…</p>}
            {!loading && error && <p className="state-message state-message--error">{error}</p>}
            {!loading && !error && !hasWeeks && (
                <p className="state-message">No InCenter release weeks are recorded in “{sheetName}” yet.</p>
            )}
            {!loading && !error && hasWeeks && (
                <>
                    <div className="chart-canvas">
                        <Line
                            plugins={[dumbbellPlugin]}
                            data={chartData}
                            options={{
                                responsive: true,
                                maintainAspectRatio: false,
                                interaction: { mode: 'nearest', intersect: true },
                                layout: { padding: { top: 18, right: 12, bottom: 0, left: 0 } },
                                plugins: {
                                    legend: { display: false },
                                    tooltip: {
                                        backgroundColor: '#0f172a',
                                        titleFont: { family: FONT_FAMILY, size: 12.5, weight: 'bold' },
                                        bodyFont: { family: FONT_FAMILY, size: 12 },
                                        padding: 10,
                                        cornerRadius: 8,
                                        boxPadding: 4,
                                        callbacks: {
                                            label: (ctx) => {
                                                const value = ctx.parsed.y as number | null;
                                                if (value === null) return `${ctx.dataset.label}: not set`;
                                                if (ctx.dataset.label !== 'Actual') return `Planned: ${formatWeekIndex(value)}`;
                                                const planWeek = schedule.products[ctx.dataIndex]?.plannedWeekIndex;
                                                if (planWeek === null || planWeek === undefined) {
                                                    return `Actual: ${formatWeekIndex(value)} (no plan to compare)`;
                                                }
                                                const delta = value - planWeek;
                                                const deltaText = delta === 0 ? 'on time' : delta > 0 ? `${delta} wk late` : `${Math.abs(delta)} wk early`;
                                                return `Actual: ${formatWeekIndex(value)} (${deltaText})`;
                                            },
                                        },
                                    },
                                },
                                scales: {
                                    x: {
                                        type: 'category',
                                        offset: true,
                                        ticks: { color: '#334155', font: { family: FONT_FAMILY, size: 12, weight: 600 } },
                                        grid: { display: false },
                                        border: { color: '#e2e8f0' },
                                    },
                                    y: {
                                        min: tickValues[0] - 2,
                                        max: tickValues[tickValues.length - 1] + 2,
                                        afterBuildTicks: (axis) => {
                                            axis.ticks = tickValues.map((v) => ({ value: v }));
                                        },
                                        ticks: {
                                            callback: (value) => formatWeekIndex(Number(value)),
                                            color: AXIS_TEXT_COLOR,
                                            font: { family: FONT_FAMILY, size: 11.5 },
                                            padding: 8,
                                        },
                                        grid: { color: GRID_COLOR },
                                        border: { display: false },
                                    },
                                },
                            }}
                        />
                    </div>
                    <ul className="legend legend--footer" aria-label="Chart legend">
                        <li className="legend__item"><span className="legend__ring" />Planned</li>
                        {schedule.hasActualColumn && (
                            <>
                                <li className="legend__item"><span className="legend__swatch legend__swatch--on-time" />Actual — on time or early</li>
                                <li className="legend__item"><span className="legend__swatch legend__swatch--late" />Actual — later than planned</li>
                            </>
                        )}
                        <li className="legend__item legend__item--muted">Dotted line links each point to its OS version</li>
                    </ul>
                </>
            )}
        </section>
    );
};

export default QuarterlyScheduleChart;
