// TypeScript generated by Copilot
import React, { useEffect, useMemo, useState } from 'react';
import { Line } from 'react-chartjs-2';
import {
    Chart as ChartJS,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    Tooltip,
    Legend,
} from 'chart.js';
import { getXlsxBytes, loadXLSX } from './ServicePackXlsxView';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Tooltip, Legend);

// Column layout varies per quarter sheet (Q3/Q4 currently have a trailing
// "Actual" column that Q1/Q2 don't have yet) — the "InCenter release" and
// "Actual" columns are discovered from the sheet's own header row rather than
// assumed by fixed position, since the live workbook's schema differs across
// quarters and will keep changing as it's updated.
//
// This chart deliberately plots only the InCenter release milestone (Planned
// vs. Actual) per OS version, as a dumbbell/lollipop: a muted dot for Planned
// and a colour-coded dot for Actual, joined by a thin connector line. The
// other phases (Scope Finalized, Development, Integration, Verification,
// Validation, Production release) remain visible in the detailed status
// table rendered below the chart, just not on it.
const HEADER_LABEL = 'product';
const PLAN_LABEL = 'plan';
const ACTUAL_LABEL = 'actual';
const INCENTER_PHASE = 'InCenter release';

const PLANNED_DOT_COLOR = '#94a3b8';
const LATE_COLOR = '#e11d48';
const ON_TIME_COLOR = '#0d9488';
const UNKNOWN_COMPARISON_COLOR = '#94a3b8';

// Earliest year observed in the planning data — used to turn "Wk NN'YYYY"
// labels into a single continuous, sortable number for the Y axis.
const BASE_YEAR = 2025;

interface ProductSchedule {
    product: string;
    plannedWeekIndex: number | null;
    actualWeekIndex: number | null;
}

interface QuarterSheetData {
    products: ProductSchedule[];
    hasActualColumn: boolean;
}

const parseWeekLabel = (label: string): number | null => {
    const m = /wk\s*(\d{1,2})\s*'\s*(\d{4})/i.exec(label);
    if (!m) return null; // e.g. a bare "2025" placeholder — not a week, left out of the chart
    const week = parseInt(m[1], 10);
    const year = parseInt(m[2], 10);
    return (year - BASE_YEAR) * 52 + week;
};

// Discovers this sheet's real column layout from its own header row(s) —
// a sheet may repeat the header mid-way with a longer column set the second
// time (e.g. adding "Actual"); the first non-blank name seen per column wins.
const discoverColumns = (rows: string[][]): { incenterColumnIndex: number; actualColumnIndex: number } => {
    const columnNames: (string | null)[] = [];
    for (const row of rows) {
        const cell0 = String(row[0] ?? '').trim();
        if (cell0.toLowerCase() !== HEADER_LABEL) continue;
        row.forEach((raw, idx) => {
            if (idx === 0) return;
            const name = String(raw ?? '').trim();
            if (name && !columnNames[idx]) columnNames[idx] = name;
        });
    }

    let actualColumnIndex = -1;
    let incenterColumnIndex = -1;
    columnNames.forEach((name, idx) => {
        if (idx === 0 || !name) return;
        if (name.toLowerCase() === ACTUAL_LABEL) actualColumnIndex = idx;
        else if (name === INCENTER_PHASE) incenterColumnIndex = idx;
    });
    return { incenterColumnIndex, actualColumnIndex };
};

// Groups the sheet's repeating (status-row, plan-row) pairs into one entry per
// product/OS version, then keeps only the InCenter release plan week and the
// Actual week (when present). Handles the sheet's real-world irregularities:
// repeated "Product" header rows, blank separator rows, and plan rows whose
// first cell is blank rather than the literal word "Plan".
const parseQuarterSchedule = (rows: string[][]): QuarterSheetData => {
    const { incenterColumnIndex, actualColumnIndex } = discoverColumns(rows);
    const products: ProductSchedule[] = [];
    let current: ProductSchedule | null = null;

    for (const row of rows) {
        const cell0 = String(row[0] ?? '').trim();
        const dataCells = row.slice(1);
        const rowHasData = dataCells.some((c) => String(c ?? '').trim() !== '');

        if (!cell0 && !rowHasData) continue; // blank separator row
        if (cell0.toLowerCase() === HEADER_LABEL) continue; // repeated cosmetic header row

        if (cell0 && cell0.toLowerCase() !== PLAN_LABEL) {
            // A new product/OS version status row — starts a new group.
            current = { product: cell0, plannedWeekIndex: null, actualWeekIndex: null };
            products.push(current);
            continue;
        }

        // Plan/week row for the most recently started product group.
        if (!current) continue;

        if (incenterColumnIndex >= 0) {
            const label = String(row[incenterColumnIndex] ?? '').trim();
            if (label) {
                const weekIndex = parseWeekLabel(label);
                if (weekIndex !== null) current.plannedWeekIndex = weekIndex;
            }
        }
        if (actualColumnIndex >= 0) {
            const label = String(row[actualColumnIndex] ?? '').trim();
            if (label) {
                const weekIndex = parseWeekLabel(label);
                if (weekIndex !== null) current.actualWeekIndex = weekIndex;
            }
        }
    }
    return { products, hasActualColumn: actualColumnIndex >= 0 };
};

const formatWeekIndex = (weekIndex: number): string => {
    const zeroBased = weekIndex - 1;
    const year = BASE_YEAR + Math.floor(zeroBased / 52);
    const week = (zeroBased % 52) + 1;
    return `Wk${week}'${String(year).slice(-2)}`;
};

const comparisonColor = (p: ProductSchedule): string => {
    if (p.actualWeekIndex === null) return 'transparent';
    if (p.plannedWeekIndex === null) return UNKNOWN_COMPARISON_COLOR;
    return p.actualWeekIndex > p.plannedWeekIndex ? LATE_COLOR : ON_TIME_COLOR;
};

interface Props {
    sheetName: string;
    title?: string;
}

const QuarterlyScheduleChart: React.FC<Props> = ({ sheetName, title }) => {
    const [sheetData, setSheetData] = useState<QuarterSheetData | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string>('');

    useEffect(() => {
        let cancelled = false;
        setLoading(true);
        setError('');
        setSheetData(null);

        Promise.all([getXlsxBytes(), loadXLSX()])
            .then(([bytes, XLSX]) => {
                if (cancelled) return;
                const workbook = XLSX.read(bytes, { type: 'array' });
                const sheet = workbook.Sheets[sheetName];
                if (!sheet) {
                    throw new Error(`Sheet "${sheetName}" not found.`);
                }
                const rawRows = XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '' }) as string[][];
                setSheetData(parseQuarterSchedule(rawRows));
            })
            .catch((err) => {
                if (!cancelled) setError(err?.message || 'Failed to load schedule data.');
            })
            .finally(() => {
                if (!cancelled) setLoading(false);
            });

        return () => { cancelled = true; };
    }, [sheetName]);

    // Only show real observed week values as Y-axis ticks (not arbitrary
    // rounded numbers), so every tick reads as a genuine "Wk NN'YY" label.
    const tickValues = useMemo(() => {
        if (!sheetData) return [];
        const all = new Set<number>();
        sheetData.products.forEach((p) => {
            if (p.plannedWeekIndex !== null) all.add(p.plannedWeekIndex);
            if (p.actualWeekIndex !== null) all.add(p.actualWeekIndex);
        });
        return Array.from(all).sort((a, b) => a - b);
    }, [sheetData]);

    const chartData = useMemo(() => {
        if (!sheetData || sheetData.products.length === 0) return null;
        const { products, hasActualColumn } = sheetData;

        const plannedDataset = {
            label: 'Planned (InCenter release)',
            data: products.map((p) => p.plannedWeekIndex),
            showLine: false,
            pointBackgroundColor: PLANNED_DOT_COLOR,
            pointBorderColor: '#ffffff',
            pointBorderWidth: 2,
            pointRadius: 7,
            pointHoverRadius: 9,
            order: 1,
        };

        if (!hasActualColumn) {
            return { labels: products.map((p) => p.product), datasets: [plannedDataset] };
        }

        const pointColors = products.map(comparisonColor);
        const actualDataset = {
            label: 'Actual',
            data: products.map((p) => p.actualWeekIndex),
            showLine: false,
            pointBackgroundColor: pointColors,
            pointBorderColor: '#ffffff',
            pointBorderWidth: 2,
            pointRadius: 7,
            pointHoverRadius: 9,
            order: 0,
        };

        return { labels: products.map((p) => p.product), datasets: [plannedDataset, actualDataset] };
    }, [sheetData]);

    // Draws the thin connector line between the Planned and Actual dots for
    // each OS version (the "dumbbell" bar), plus a week label above/below
    // each endpoint — registered as a chart-local plugin, so it never
    // affects any other chart instance on the page.
    const dumbbellPlugin = useMemo(() => ({
        id: 'schedule-chart-dumbbell',
        beforeDatasetsDraw(chart: any) {
            if (!sheetData) return;
            const { ctx, chartArea } = chart;
            const plannedMeta = chart.getDatasetMeta(0);
            const actualMeta = chart.data.datasets.length > 1 ? chart.getDatasetMeta(1) : null;

            // Dotted stem from the x-axis up to each OS version's topmost dot —
            // makes it easy to trace which category a dot belongs to, the way a
            // lollipop/stem chart anchors each value to its baseline.
            ctx.save();
            ctx.setLineDash([3, 3]);
            ctx.lineWidth = 1;
            ctx.strokeStyle = '#cbd5e1';
            sheetData.products.forEach((p, i) => {
                const plannedEl = p.plannedWeekIndex !== null ? plannedMeta.data[i] : null;
                const actualEl = actualMeta && p.actualWeekIndex !== null ? actualMeta.data[i] : null;
                const topEl = [plannedEl, actualEl].filter(Boolean).sort((a: any, b: any) => a.y - b.y)[0];
                if (!topEl) return;
                ctx.beginPath();
                ctx.moveTo(topEl.x, chartArea.bottom);
                ctx.lineTo(topEl.x, topEl.y);
                ctx.stroke();
            });
            ctx.restore();

            if (!sheetData.hasActualColumn) return;
            ctx.save();
            sheetData.products.forEach((p, i) => {
                if (p.actualWeekIndex === null || p.plannedWeekIndex === null) return;
                const from = plannedMeta.data[i];
                const to = actualMeta.data[i];
                if (!from || !to) return;
                ctx.beginPath();
                ctx.moveTo(from.x, from.y);
                ctx.lineTo(to.x, to.y);
                ctx.lineWidth = 3;
                ctx.strokeStyle = comparisonColor(p);
                ctx.globalAlpha = 0.35;
                ctx.stroke();
            });
            ctx.restore();
        },
        afterDatasetsDraw(chart: any) {
            if (!sheetData) return;
            const { ctx } = chart;
            const plannedMeta = chart.getDatasetMeta(0);
            const actualMeta = chart.data.datasets.length > 1 ? chart.getDatasetMeta(1) : null;
            ctx.save();
            ctx.font = "600 10.5px 'Segoe UI', system-ui, sans-serif";
            ctx.textAlign = 'center';
            sheetData.products.forEach((p, i) => {
                const plannedEl = plannedMeta.data[i];
                const actualEl = actualMeta ? actualMeta.data[i] : null;
                const hasActual = p.actualWeekIndex !== null && actualEl;
                const hasPlanned = p.plannedWeekIndex !== null && plannedEl;
                if (!hasPlanned && !hasActual) return;

                const actualColor = comparisonColor(p) === 'transparent' ? '#334155' : comparisonColor(p);
                const planLabel = `Plan ${formatWeekIndex(p.plannedWeekIndex!)}`;
                const actualLabel = `Actual ${formatWeekIndex(p.actualWeekIndex!)}`;

                if (hasPlanned && hasActual) {
                    const coincide = Math.abs(plannedEl.y - actualEl!.y) < 4;
                    if (coincide) {
                        // Same position — stack both labels around the single visible dot.
                        ctx.fillStyle = actualColor;
                        ctx.fillText(actualLabel, actualEl!.x, actualEl!.y - 14);
                        ctx.fillStyle = PLANNED_DOT_COLOR;
                        ctx.fillText(planLabel, plannedEl.x, plannedEl.y + 22);
                    } else {
                        // Distinct positions — label each dot on the side facing away
                        // from the other, so the two labels never overlap each other
                        // or the connector line between them.
                        const plannedAbove = plannedEl.y < actualEl!.y;
                        ctx.fillStyle = PLANNED_DOT_COLOR;
                        ctx.fillText(planLabel, plannedEl.x, plannedAbove ? plannedEl.y - 12 : plannedEl.y + 22);
                        ctx.fillStyle = actualColor;
                        ctx.fillText(actualLabel, actualEl!.x, plannedAbove ? actualEl!.y + 22 : actualEl!.y - 12);
                    }
                } else if (hasPlanned) {
                    ctx.fillStyle = PLANNED_DOT_COLOR;
                    ctx.fillText(planLabel, plannedEl.x, plannedEl.y - 12);
                } else if (hasActual) {
                    ctx.fillStyle = actualColor;
                    ctx.fillText(actualLabel, actualEl!.x, actualEl!.y - 12);
                }
            });
            ctx.restore();
        },
    }), [sheetData]);

    if (loading) {
        return <div className="xlsx-state xlsx-state--loading">Loading {title || sheetName} chart…</div>;
    }
    if (error) {
        return <div className="xlsx-state xlsx-state--error">{error}</div>;
    }
    if (!chartData || tickValues.length === 0) {
        return <div className="xlsx-state xlsx-state--empty">No InCenter release week data found in "{sheetName}" yet.</div>;
    }

    return (
        <section className="schedule-chart">
            <div className="schedule-chart__header">
                {title && <h3 className="schedule-chart__title">{title}</h3>}
                <p className="schedule-chart__subtitle">InCenter release — planned vs. actual, by OS version</p>
            </div>
            <div className="schedule-chart__canvas-wrap">
                <Line
                    plugins={[dumbbellPlugin]}
                    data={chartData}
                    options={{
                        responsive: true,
                        maintainAspectRatio: false,
                        interaction: { mode: 'nearest', intersect: true },
                        layout: { padding: { top: 24, right: 20, bottom: 28, left: 4 } },
                        plugins: {
                            legend: { display: false },
                            tooltip: {
                                backgroundColor: '#1e293b',
                                titleFont: { size: 13, weight: 'bold' },
                                bodyFont: { size: 12.5 },
                                padding: 10,
                                cornerRadius: 8,
                                displayColors: true,
                                callbacks: {
                                    label: (ctx) => {
                                        const value = ctx.parsed.y as number | null;
                                        if (ctx.dataset.label === 'Actual') {
                                            if (value === null) return 'Actual: not yet available';
                                            const planWeek = sheetData?.products[ctx.dataIndex]?.plannedWeekIndex;
                                            if (planWeek === null || planWeek === undefined) {
                                                return `Actual: ${formatWeekIndex(value)} (no plan to compare)`;
                                            }
                                            const delta = value - planWeek;
                                            const deltaText = delta === 0 ? 'on time' : delta > 0 ? `${delta}wk late` : `${Math.abs(delta)}wk early`;
                                            return `Actual: ${formatWeekIndex(value)} (${deltaText})`;
                                        }
                                        return value === null
                                            ? 'Planned: not yet set'
                                            : `Planned: ${formatWeekIndex(value)}`;
                                    },
                                },
                            },
                        },
                        scales: {
                            x: {
                                type: 'category',
                                offset: true,
                                title: {
                                    display: true,
                                    text: 'OS Version',
                                    color: '#64748b',
                                    font: { size: 12.5, weight: 'bold' },
                                },
                                ticks: { color: '#475569', font: { size: 11.5 } },
                                grid: { display: false },
                            },
                            y: {
                                min: (tickValues[0] ?? 0) - 2,
                                max: (tickValues[tickValues.length - 1] ?? 0) + 2,
                                title: {
                                    display: true,
                                    text: 'Week',
                                    color: '#64748b',
                                    font: { size: 12.5, weight: 'bold' },
                                },
                                afterBuildTicks: (axis) => {
                                    axis.ticks = tickValues.map((v) => ({ value: v }));
                                },
                                ticks: {
                                    callback: (value) => formatWeekIndex(Number(value)),
                                    color: '#475569',
                                    font: { size: 11.5 },
                                },
                                grid: { color: '#f1f4f9' },
                            },
                        },
                    }}
                />
            </div>
            <p className="schedule-chart__caption">
                <span className="schedule-chart__caption-item">
                    <span className="schedule-chart__legend-dot schedule-chart__legend-dot--planned" />
                    Planned (InCenter release)
                </span>
                {sheetData?.hasActualColumn && (
                    <>
                        <span className="schedule-chart__caption-item">
                            <span className="schedule-chart__legend-dot schedule-chart__legend-dot--ontime" />
                            Actual on time or early
                        </span>
                        <span className="schedule-chart__caption-item">
                            <span className="schedule-chart__legend-dot schedule-chart__legend-dot--late" />
                            Actual later than planned
                        </span>
                    </>
                )}
            </p>
        </section>
    );
};

export default QuarterlyScheduleChart;
