// TypeScript generated by Copilot
import React from 'react';
import { CheckIcon, CycleIcon } from './icons';
import { osToneClass } from './osTone';
import './ServicePackOverview.css';

interface OsRelease {
  os: string;
  /** Display label for the end of life, e.g. "Oct 2026". */
  eol?: string;
  /** End-of-life month as YYYY-MM, used to find the next upcoming EOL. */
  eolMonth?: string;
  /** Shown instead of the quarterly markers when the cadence is conditional. */
  note?: string;
}

const RELEASES: OsRelease[] = [
  { os: 'Windows 10 1607', eol: 'Oct 2026', eolMonth: '2026-10' },
  { os: 'Windows 10 1809', eol: 'Jan 2029', eolMonth: '2029-01' },
  { os: 'Windows 10 2021', eol: 'Jan 2032', eolMonth: '2032-01' },
  { os: 'Windows 11 2024', eol: 'Oct 2034', eolMonth: '2034-10', note: 'Per quarter, post Elua RFD' },
  { os: 'Future OS releases', note: 'Per quarter, as applicable' },
];

const QUARTERS = ['Q1', 'Q2', 'Q3', 'Q4'];

const PRINCIPLES = [
  'Follow a 90-day release cadence',
  'Be released per OS version until the OS end of life',
  'Mandatorily contain Microsoft patches',
  'Include pre-planned security fixes and minor enhancements',
  'Not be used to handle obsolescence',
];

const currentMonth = (): string => {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
};

const nextEndOfLife = (): OsRelease | undefined => {
  const month = currentMonth();
  return RELEASES
    .filter((r) => r.eolMonth && r.eolMonth >= month)
    .sort((a, b) => a.eolMonth!.localeCompare(b.eolMonth!))[0];
};

const ServicePackOverview: React.FC = () => {
  const next = nextEndOfLife();

  return (
    <div className="strategy">
      <div className="kpi-grid kpi-grid--single">
        <div className="card kpi kpi--blue">
          <span className="kpi__icon"><CycleIcon /></span>
          <span className="kpi__label">Release cadence</span>
          <span className="kpi__value">90 days</span>
          <span className="kpi__hint">One service pack per OS version, every quarter</span>
        </div>
      </div>

      <div className="strategy__layout">
        <section className="card">
          <div className="card__header">
            <div>
              <h2 className="card__title">Release cadence by OS version</h2>
              <p className="card__subtitle">Each marker is a planned service pack release in that quarter.</p>
            </div>
          </div>

          <div className="cadence" role="table" aria-label="Service pack release cadence by OS version">
            <div className="cadence__row cadence__row--head" role="row">
              <span role="columnheader">OS version</span>
              <span role="columnheader">End of life</span>
              {QUARTERS.map((q) => <span key={q} role="columnheader" className="cadence__quarter-head">{q}</span>)}
            </div>
            {RELEASES.map((release) => (
              <div key={release.os} className={`cadence__row ${osToneClass(release.os)}`} role="row">
                <span role="rowheader" className="cadence__os">
                  <span className="os-swatch" aria-hidden="true" />
                  {release.os}
                </span>
                <span role="cell" className={release.eol ? 'cadence__eol' : 'cadence__eol cadence__eol--none'}>
                  {release === next ? (
                    <span className="eol-pill" title="Next upcoming end of life">{release.eol}</span>
                  ) : (release.eol ?? '—')}
                </span>
                {release.note ? (
                  <span role="cell" className="cadence__track cadence__track--conditional">
                    <span className="cadence__note">{release.note}</span>
                  </span>
                ) : (
                  <span role="cell" className="cadence__track">
                    {QUARTERS.map((q) => (
                      <span key={q} className="cadence__slot">
                        <span className="cadence__marker" title={`${release.os}: ${q} service pack`} />
                      </span>
                    ))}
                  </span>
                )}
              </div>
            ))}
          </div>

          <p className="card__footnote">SP — Service Pack · OS — Operating System · EOL — End of Life</p>
        </section>

        <section className="card principles">
          <div className="card__header">
            <div>
              <h2 className="card__title">Service packs will</h2>
              <p className="card__subtitle">Guiding principles for every release.</p>
            </div>
          </div>
          <ul className="principles__list">
            {PRINCIPLES.map((item) => (
              <li key={item} className="principles__item">
                <span className="principles__icon"><CheckIcon /></span>
                {item}
              </li>
            ))}
          </ul>
        </section>
      </div>
    </div>
  );
};

export default ServicePackOverview;
