// TypeScript generated by Copilot
import React from 'react';
import { useWorkbookSheet } from '../hooks/useWorkbookSheet';
import { StatusBadge } from './QuarterStatusTable';
import { cellText, statusTone } from './quarterSheet';
import { osToneClass } from './osTone';
import { CalendarIcon } from './icons';

// The workbook loader/cache lives in data/workbook; re-exported here so
// existing imports of these helpers keep working.
export { loadXLSX, getXlsxBytes, getXlsxFetchMeta, invalidateXlsxCache } from '../data/workbook';
export type { XlsxFetchMeta } from '../data/workbook';

const QUARTER_HEADER = /^q([1-4])$/i;

const splitItems = (value: string): string[] => value.split(/\s*,\s*/).filter(Boolean);

/** Service pack names in a cell; status words (e.g. "Completed") are not counted. */
const servicePacks = (value: string): string[] => splitItems(value).filter((item) => statusTone(item) === 'neutral');

const PlanCell: React.FC<{ value: string }> = ({ value }) => {
    const items = splitItems(value);
    if (items.length === 0) return <span className="cell-empty">—</span>;
    return (
        <span className="tag-list">
            {items.map((item) => (statusTone(item) === 'neutral'
                ? <span key={item} className="tag tag--os">{item}</span>
                : <StatusBadge key={item} value={item} />))}
        </span>
    );
};

const QuarterHeader: React.FC<{ label: string; current: boolean }> = ({ label, current }) => {
    const match = QUARTER_HEADER.exec(label);
    if (!match) return <>{label}</>;
    return (
        <span className={`plan-quarter plan-quarter--q${match[1]}`}>
            <span className="plan-quarter__dot" aria-hidden="true" />
            {label}
            {current && <span className="current-chip">NOW</span>}
        </span>
    );
};

interface Props {
    sheetName: string;
    title?: string;
    subtitle?: string;
    /** Year the plan sheet covers; the current quarter is highlighted when it matches today. */
    planYear?: number;
    /** Bump this (e.g. a counter) to force a re-fetch after invalidateXlsxCache(). */
    refreshToken?: number;
}

/** Renders the plan matrix sheet: first row = quarter headers, first column = OS version. */
const ServicePackXlsxView: React.FC<Props> = ({ sheetName, title, subtitle, planYear, refreshToken }) => {
    const { rows, loading, error } = useWorkbookSheet(sheetName, refreshToken);
    const cells = rows
        .map((row) => row.map(cellText))
        .filter((row) => row.some((cell) => cell !== ''));
    const width = cells.reduce((max, row) => Math.max(max, row.length), 0);
    const [headerRow = [], ...bodyRows] = cells;
    const header = Array.from({ length: width }, (_, idx) => headerRow[idx] || (idx === 0 ? 'OS version' : ''));

    const now = new Date();
    const currentQuarter = planYear === now.getFullYear() ? `q${Math.floor(now.getMonth() / 3) + 1}` : '';
    const isCurrent = (label: string) => currentQuarter !== '' && label.toLowerCase() === currentQuarter;

    const totalPlanned = header.slice(1).reduce((total, _, colIdx) =>
        total + bodyRows.reduce((sum, row) => sum + servicePacks(row[colIdx + 1] ?? '').length, 0), 0);

    const hasData = !loading && !error && bodyRows.length > 0;

    return (
        <div className="page-stack">
            {hasData && (
                <div className="kpi-grid kpi-grid--single">
                    <div className="card kpi kpi--blue">
                        <span className="kpi__icon"><CalendarIcon /></span>
                        <span className="kpi__label">Service packs planned</span>
                        <span className="kpi__value">{totalPlanned}</span>
                        <span className="kpi__hint">Across all quarters{planYear ? ` of ${planYear}` : ''}</span>
                    </div>
                </div>
            )}

            <section className="card">
                {(title || subtitle) && (
                    <div className="card__header">
                        <div>
                            {title && <h2 className="card__title">{title}</h2>}
                            {subtitle && <p className="card__subtitle">{subtitle}</p>}
                        </div>
                    </div>
                )}
                {loading && <p className="state-message">Loading…</p>}
                {!loading && error && <p className="state-message state-message--error">{error}</p>}
                {!loading && !error && bodyRows.length === 0 && (
                    <p className="state-message">No data found in “{sheetName}”.</p>
                )}
                {hasData && (
                    <div className="table-scroll">
                        <table className="data-table data-table--matrix">
                            <thead>
                                <tr>
                                    {header.map((cell, idx) => {
                                        const className = [idx === 0 && 'data-table__sticky', idx > 0 && isCurrent(cell) && 'data-table__current']
                                            .filter(Boolean).join(' ');
                                        return (
                                            <th key={idx} scope="col" className={className || undefined}>
                                                {idx === 0 ? cell : <QuarterHeader label={cell} current={isCurrent(cell)} />}
                                            </th>
                                        );
                                    })}
                                </tr>
                            </thead>
                            <tbody>
                                {bodyRows.map((row, rowIdx) => (
                                    <tr key={rowIdx} className={osToneClass(row[0] ?? '')}>
                                        <th scope="row" className="data-table__sticky">
                                            <span className="os-label">
                                                <span className="os-swatch" aria-hidden="true" />
                                                {row[0]}
                                            </span>
                                        </th>
                                        {header.slice(1).map((label, colIdx) => (
                                            <td key={colIdx} className={isCurrent(label) ? 'data-table__current' : undefined}>
                                                <PlanCell value={row[colIdx + 1] ?? ''} />
                                            </td>
                                        ))}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </section>
        </div>
    );
};

export default ServicePackXlsxView;
