// TypeScript generated by Copilot
// Loads each workbook once per page session and shares the bytes across
// every view; invalidateXlsxCache() forces the next read to refetch.

const SHEETJS_URL = 'https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';

/** API route per workbook; each reads its configured share path or the bundled copy. */
export const WORKBOOK_URLS = {
    planning: '/api/service-pack-xlsx',
    ibSystemVersions: '/api/ib-system-versions-xlsx',
} as const;

export type WorkbookId = keyof typeof WORKBOOK_URLS;

export const loadXLSX = (): Promise<any> => {
    const existing = (window as any).XLSX;
    if (existing) return Promise.resolve(existing);
    return new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = SHEETJS_URL;
        script.onload = () => {
            const lib = (window as any).XLSX;
            lib ? resolve(lib) : reject(new Error('SheetJS failed to load.'));
        };
        script.onerror = () => reject(new Error('Could not load the spreadsheet library.'));
        document.body.appendChild(script);
    });
};

const cachedBytes = new Map<WorkbookId, Uint8Array>();
const inflight = new Map<WorkbookId, Promise<Uint8Array>>();

// Populated from the API response's `source` field ("external" | "bundled" |
// "bundled-fallback") and the time of the last successful fetch.
export interface XlsxFetchMeta {
    source: string;
    fetchedAt: Date;
}
const lastFetchMeta = new Map<WorkbookId, XlsxFetchMeta>();
export const getXlsxFetchMeta = (id: WorkbookId = 'planning'): XlsxFetchMeta | null => lastFetchMeta.get(id) ?? null;

/** Drops every cached workbook so the next read of each refetches. */
export const invalidateXlsxCache = (): void => {
    cachedBytes.clear();
    inflight.clear();
};

export const getXlsxBytes = (id: WorkbookId = 'planning'): Promise<Uint8Array> => {
    const cached = cachedBytes.get(id);
    if (cached) return Promise.resolve(cached);
    const pending = inflight.get(id);
    if (pending) return pending;
    const request = fetch(WORKBOOK_URLS[id])
        .then((res) => {
            if (!res.ok) throw new Error(`Server returned ${res.status}. Make sure the Express server is running (npm run server).`);
            return res.json();
        })
        .then((payload: { dataBase64: string; source: string }) => {
            const binary = window.atob(payload.dataBase64);
            const bytes = new Uint8Array(binary.length);
            for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
            cachedBytes.set(id, bytes);
            lastFetchMeta.set(id, { source: payload.source, fetchedAt: new Date() });
            return bytes;
        })
        .catch((err) => {
            inflight.delete(id); // allow retry on next read
            throw err;
        });
    inflight.set(id, request);
    return request;
};
